Application structure
evensaldanha/product-manager pull request #1
Opened 2024-01-16 17:20 UTC by evensaldanha

Criei a estrutura do projeto, utilizando MI e Mi-Icon.

2024-01-16 23:10 UTC, Yuri-Ribeiro requested changes

2024-01-16 23:10 UTC, Yuri-Ribeiro commented on package.json
> +    "next": "14.0.4",
Deixe as versões fixas, pra no futuro não ter problema com atualizacões dessas bibliotecas

```suggestion
    "@emotion/react": "11.11.3",
    "@emotion/styled": "11.11.0",
    "@mui/material": "5.15.4",
    "material-icons": "1.13.12",
    "next": "14.0.4",
```

2024-01-16 23:10 UTC, Yuri-Ribeiro commented on package.json
>      "react": "^18",
Mesma coisa, deixe fixa

```suggestion
    "react": "18",
```

2024-01-16 23:10 UTC, Yuri-Ribeiro commented on package.json
> +    "react-dom": "^18"
Mesma coisa, deixe fixa

```suggestion
    "react-dom": "18"
```

2024-01-16 23:10 UTC, Yuri-Ribeiro commented on package.json
>      "tailwindcss": "^3.3.0",
Mesma coisa, deixe-as fixa

```suggestion
    "@types/node": "20",
    "@types/react": "18",
    "@types/react-dom": "18",
    "autoprefixer": "10.0.1",
    "eslint": "8",
    "eslint-config-next": "14.0.4",
    "postcss": "8",
    "tailwindcss": "3.3.0",
```

2024-01-16 23:10 UTC, Yuri-Ribeiro commented on package.json
> +    "typescript": "^5"
Mesma coisa, deixe fixa

```suggestion
    "typescript": "5"
```

2024-01-16 23:10 UTC, Yuri-Ribeiro commented on src/app/page.tsx
> +    setAmount(event.target.value as string);
pra evitar bugs, é melhor checar se o tipo realmente é string antes de alterar `amount`:

```suggestion
    if (typeof event.target.value === 'string') setAmount(event.target.value);
```

2024-01-16 23:10 UTC, Yuri-Ribeiro commented on src/app/page.tsx
> +        <InputLabel id="demo-simple-select-label">Quantidade</InputLabel>
esses ids que tá usando são realmente necessários? parece de algum exemplo que pegou

2024-01-17 22:44 UTC, evensaldanha commented on src/app/page.tsx
> +    setAmount(event.target.value as string);
No caso será a quantidase de produtos, mas lembro que vc disse uma vez seria melhor colcoar como string msm sendo numero

2024-01-17 23:45 UTC, merged